"""empty message

Revision ID: 2d609c7cf768
Revises: 1bdc5d0e9dda
Create Date: 2018-10-13 23:13:12.218626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d609c7cf768'
down_revision = '1bdc5d0e9dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('description', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'description')
    # ### end Alembic commands ###
