"""empty message

Revision ID: 46463e660d78
Revises: 85fa33c10093
Create Date: 2018-10-14 00:58:57.025340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46463e660d78'
down_revision = '85fa33c10093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_episode_id'), 'episode', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episode_id'), table_name='episode')
    # ### end Alembic commands ###
