"""empty message

Revision ID: 7b17f8a0a049
Revises: bb2a6114fa4a
Create Date: 2018-10-14 20:19:43.186738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b17f8a0a049'
down_revision = 'bb2a6114fa4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('banner', sa.Unicode(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'banner')
    # ### end Alembic commands ###
