"""empty message

Revision ID: 9277d2e3db0c
Revises: ac1a017bdc76
Create Date: 2018-10-13 22:44:01.008364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9277d2e3db0c'
down_revision = 'ac1a017bdc76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'image',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'image',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###
