"""empty message

Revision ID: a8eb42c36ec7
Revises: e7027eb76ee7
Create Date: 2018-10-14 00:45:34.294515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8eb42c36ec7'
down_revision = 'e7027eb76ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video', sa.Unicode(length=180), nullable=False),
    sa.Column('quality_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quality_id'], ['quality.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('episode', 'anime_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episode', 'anime_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('video')
    # ### end Alembic commands ###
