"""empty message

Revision ID: e2e970249fad
Revises: 55ffffa253e1
Create Date: 2018-10-13 23:49:17.825455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e970249fad'
down_revision = '55ffffa253e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Unicode(length=128), nullable=False),
    sa.Column('number', sa.Float(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episode')
    # ### end Alembic commands ###
