"""empty message

Revision ID: e7027eb76ee7
Revises: e2e970249fad
Create Date: 2018-10-14 00:39:08.604792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7027eb76ee7'
down_revision = 'e2e970249fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_name'), 'quality', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_name'), table_name='quality')
    op.drop_table('quality')
    # ### end Alembic commands ###
